spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SharmaEcommerce?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: aviral123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # update, create, create-drop, validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

razorpay:
  key-id: rzp_test_6t9QBuverngKfv
  key-secret: IiF53JKSeZGKI8NmBbN0tlRX
